config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'hauntedhouses#index'

  resources :hauntedhouses, only: [:index, :show, :new, :edit, :update, :create, :destroy ] do
    resources :journeys, only: [:show, :new, :create] 
    collection do
      get :hauntedlist
    end
  end
  resources :journeys, only: [:index, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hauntedhouse.rb
class Hauntedhouse < ApplicationRecord
  CATEGORY = ["Frightening", "Terrifying", "Chilling", "Blood-curdling", "Deadly"]
  has_many :reviews
  has_many :journeys
  belongs_to :user

  has_one_attached :photo
  validates :category, inclusion: { in: CATEGORY }

  include PgSearch::Model
  pg_search_scope :search_by_all,
    against: [ :name, :description, :category, :address, :city, :country ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def reserved?(actuel_user)
    @journeys = self.journeys
    res = false
    if @journeys.count > 0
      @journeys.each do |journey|
        if journey.user == actuel_user
           res = journey.checkin > Date.today
        end
      end
    end
    return res
  end

end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  belongs_to :hauntedhouse
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hauntedhouse
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :journeys
  has_many :hauntedhouses

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    
end
    

app/controllers/hauntedhouses_controller.rb
class HauntedhousesController < ApplicationController

  before_action :set_hauntedhouse, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index

    if params[:query].present?
      @hauntedhouses = Hauntedhouse.search_by_all(params[:query])
    else
       @hauntedhouses = Hauntedhouse.all
       
    end

  end

  def new
      @hauntedhouse = Hauntedhouse.new
      
  end

  def hauntedlist
    if params[:query].present?
      @hauntedhouses = Hauntedhouse.search_by_all(params[:query])
    else
       @hauntedhouses = Hauntedhouse.all
    end

  end

  

  def create
    @hauntedhouse = Hauntedhouse.new(hauntedhouse_params)
    @hauntedhouse.user = current_user
    
    if @hauntedhouse.save
      redirect_to hauntedhouses_path
    else
      render :new
    end
  end

  def show
  end

  def hauntedlist
    @hauntedhouses = Hauntedhouse.all
  end


  def edit
  end

  def update
    @hauntedhouse = Hauntedhouse.find(params[:id])
    @hauntedhouse.update(hauntedhouse_params)
    redirect_to hauntedhouse_path(@hauntedhouse)
    
  end

  def destroy
    @hauntedhouse.destroy
    redirect_to hauntedhouses_path
    
  end
  


private
  def hauntedhouse_params
    params.require(:hauntedhouse).permit(:name, :description, :category, :address, :city, :country, :price_per_night, :photo)
  end

  def set_hauntedhouse
    @hauntedhouse = Hauntedhouse.find(params[:id])
    
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
 
  def index
    @journeys = Journey.where(user_id: current_user.id)
    
  end

  def new
    @journey = Journey.new
    @hauntedhouse = Hauntedhouse.find(params[:hauntedhouse_id])
    
  end

  def create
    @hauntedhouse = Hauntedhouse.find(params[:hauntedhouse_id])
    @journey = Journey.new(journey_params)
    

    @journey.hauntedhouse = @hauntedhouse

    yin = params[:journey]["checkin(1i)"].to_i
    min = params[:journey]["checkin(2i)"].to_i
    din = params[:journey]["checkin(3i)"].to_i

    @journey.checkin = Date.new(yin,min,din)

    yout = params[:journey]["checkout(1i)"].to_i
    mout = params[:journey]["checkout(2i)"].to_i
    dout = params[:journey]["checkout(3i)"].to_i

    @journey.checkout = Date.new(yout,mout,dout)

    days = @journey.checkout - @journey.checkin

    p = @hauntedhouse.price_per_night

    @journey.price = days * p

    @journey.user = current_user

    if @journey.save!
      redirect_to journeys_path
      #redirect_to  hauntedhouse_journeys_path(@hauntedhouse)
    else
      @journey = Journey.new
      render :new
    end
  end

  def update
  end

  def edit
  end

  def destroy
    @journey = Journey.find(params[:id])
    @journey.destroy
    redirect_to journeys_path
  end

  private


  def journey_params
    params.require(:journey).permit(:checkin, :checkout, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hauntedhouses/edit.html.erb
<div class = "haunted-form">
  <div class = "row">
    <div class = "col-4">
      <%= simple_form_for(@hauntedhouse) do |f| %>
        <%= f.input :name, label: "Nom" %>
        <%= f.input :description, as: :text, :input_html => { :cols => 5, :rows => 6 } %>
        <%= f.input :category, label: "Catégorie", collection: ["Frightening", "Terrifying", "Chilling", "Blood-curdling", "Deadly"] %>
        <%= f.input :address, label: "Adresse" %>
        <%= f.input :city, label: "Ville" %>
        Prix à la nuit : <%= f.number_field :price_per_night %>€
        <br>
        <br>
        <%= f.input :photo, as: :file, label: "Ajoutez une photo" %>
        <%= f.button :submit, "Valider modifications", class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/hauntedhouses/hauntedlist.html.erb
<%= render "/shared/banner" %>
<%= render "/shared/searchbar" %>
<div class = "container">
    <div class="cards">
      <% @hauntedhouses.each do |hauntedhouse| %>
      <%#affiche uniquement les maisons du proprio <% if hauntedhouse.user == current_user %>
      <% if hauntedhouse.user == current_user %>
          <% if hauntedhouse.photo.attached? %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path hauntedhouse.photo.key, height: 300, width: 400, crop: :fill %>')">
              <div>
                 <p><%= link_to hauntedhouse.name, hauntedhouse_path(hauntedhouse) %></p>
              </div>
              <div class ="tag">

                  <% if !current_user.nil? && current_user != hauntedhouse.user %>
                      <% if hauntedhouse.reserved?(current_user) %>
                        <p>Reservée</p>
                      <% end %>
                  <% end %>

              </div>

              </div>
        <% end %>
      <% end %>



<% end %>
</div>
<!-- <%= link_to new_hauntedhouse_path do %>
  <i class="fa fa-plus"> Add a new hauntedhouse</i>
<% end %><br />-->

</div>

app/views/hauntedhouses/index.html.erb
<%= render "/shared/banner" %>
<%= render "/shared/searchbar" %>
<div class = "container">
    <div class="cards">
      <% @hauntedhouses.each do |hauntedhouse| %>
      <%#affiche uniquement les maisons du proprio <% if hauntedhouse.user == current_user %>
          <% if hauntedhouse.photo.attached? %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path hauntedhouse.photo.key, height: 300, width: 400, crop: :fill %>')">
              <div>
                 <p><%= link_to hauntedhouse.name, hauntedhouse_path(hauntedhouse) %></p>
              </div>
              <div class ="tag">

                  <% if !current_user.nil? && current_user != hauntedhouse.user %>
                      <% if hauntedhouse.reserved?(current_user) %>
                        <p>Reservée</p>
                      <% end %>
                  <% end %>

              </div>

              </div>
        <% end %>
      <% end %>




</div>
<!-- <%= link_to new_hauntedhouse_path do %>
  <i class="fa fa-plus"> Add a new hauntedhouse</i>
<% end %><br />-->
</div>

app/views/hauntedhouses/new.html.erb
<div class = "haunted-form">
  <div class = "row">
    <div class = "col-4">
      <%= simple_form_for(@hauntedhouse) do |f| %>
        <%= f.input :name, label: "Nom" %>
        <%= f.input :description, as: :text, :input_html => { :cols => 5, :rows => 6 } %>
        <%= f.input :category, label: "Catégorie", collection: ["Frightening", "Terrifying", "Chilling", "Blood-curdling", "Deadly"] %>
        <%= f.input :address, label: "Adresse" %>
        <%= f.input :city, label: "Ville" %>
        Prix à la nuit : <%= f.number_field :price_per_night %>€
        <br>
        <br>
        <%= f.input :photo, as: :file, label: "Ajoutez une photo" %>
        <%= f.button :submit, "Mettre en location", class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/hauntedhouses/show.html.erb
<div class="house-show margin-top-negative">
  <div class="row">
    <div class="col-10">

      <% if @hauntedhouse.photo.attached? %>
          <div class="house-card" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path @hauntedhouse.photo.key %>');">
            <% if @hauntedhouse.user == current_user %>
             <p class="text-bold"><%= "Vous êtes l'heureux propriétaire de cette merveille "%></p>
             <% end %>
            <div class="house-description">
             
              <h1><%= @hauntedhouse.name %></h1>
              <h2><%= @hauntedhouse.country %></h2>
              <p><%= @hauntedhouse.address %>, <%= @hauntedhouse.city %></p>
            </div>
          </div>
       <% else %>
          <div class="house-card" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('https://www.businessnhmagazine.com/UploadedFiles/Articles/8151/66581491_m.jpg');">
            <div class="house-description">
              <h1><%= @hauntedhouse.name %></h1>
              <h2><%= @hauntedhouse.country %></h2>
              <p><%= @hauntedhouse.address %>, <%= @hauntedhouse.city %></p>
            </div>
          </div>
      <% end %>


      <div class="hauntedhouse-show-card">
        <h3>Quelques détails sur l'histoire de cette demeure</h3>
        <p><%= @hauntedhouse.description %></p>

        <h3>Details</h3>
        <p>Price per night : <%= @hauntedhouse.price_per_night %>€</p>
          <p>Category : <%= @hauntedhouse.category %></p>
          <% if @hauntedhouse.user != current_user %>
          <p align="center"><%= link_to "Réservez votre séjour", new_hauntedhouse_journey_path(@hauntedhouse), class: "btn btn-dark" %></p>
          <% end %>
          <p align="right"><%= link_to "Retour", hauntedhouses_path %> |  
        
        <% if @hauntedhouse.user == current_user %>
          <%= link_to "Modifier", edit_hauntedhouse_path(@hauntedhouse) %><br />
          <%= link_to "Envoyer cette maison en Enfer", hauntedhouse_path(@hauntedhouse), method: :delete, data: { confirm: "confirmer ?" } %>
        <% end %>
        </p>

      </div>
    </div>

   <!-- <div class="col-4">
      <div class="hauntedhouse-show-card">

        <form action="">
        <div class="form">

        <p>A remplacer par le formulaire journeys</p>
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From : </span>
            <input type="text" class="form-control" placeholder="25/11/2020" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon2">To : </span>
            <input type="text" class="form-control" placeholder="03/12/2020" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          </div>

          <input type="submit" value="Book" class="btn btn-dark" style="width: 100%">
        </form>
      </div>
      <div class="hauntedhouse-show-card">
        <h3>Details</h3>
        <div class="flex">
          </div>

            <p>Price per night : <%= @hauntedhouse.price_per_night %>€</p>
            <p>Category : <%= @hauntedhouse.category %></p>
      </div> -->

    </div>
  </div>
</div>

app/views/journeys/index.html.erb
<h1>Vos réservations</h1>
<div class = "col-4">
<% @journeys.each do |journey| %>
<% hauntedhouse = Hauntedhouse.find(journey.hauntedhouse_id) %>

<% if hauntedhouse.photo.attached? %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3),
          rgba(0,0,0,0.3)), url('<%= cl_image_path hauntedhouse.photo.key, height: 300, width: 400, crop: :fill %>')">
            <p> <%= link_to hauntedhouse.name, hauntedhouse_path(hauntedhouse) %></p>
             </div>

              <% else %>

             <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3),
          rgba(0,0,0,0.3)), url('https://www.businessnhmagazine.com/UploadedFiles/Articles/8151/66581491_m.jpg')">
            <p> <%= link_to hauntedhouse.name, hauntedhouse_path(hauntedhouse) %></p>

             </div>

 <% end %>
<br>
Date d'arrivée :
<%= journey.checkin %><br/>
Date de départ :
<%= journey.checkout %><br/>
Prix du séjour :
<%= journey.price %>€<br/>
<%= link_to "Annuler cette reservation", journey_path(journey), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer ?" } %>
<br>
<% end %>
</div>

app/views/journeys/new.html.erb
<h1>Journey new</h1>
<div class = "container">
  <div class = "row">
    <div class = "col-md-4 offset-md-4">
      <%= simple_form_for [@hauntedhouse, @journey] do |f| %>

        <%= f.input :checkin, as: :date %>
        <%= f.input :checkout, as: :date%>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hauntedbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Creepster&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "/shared/navbar" %>
    <%= yield %>
    <%= render "/shared/footer"%>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.businessnhmagazine.com/UploadedFiles/Articles/8151/66581491_m.jpg);">
  <div class="container">
    <h1>HAUNTED BNB</h1>
    <p>Vous aurez peur...</p>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-skull"></i> at HauntedHouses
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to hauntedhouses_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dsmxleyf5/image/upload/v1606229418/hlg1yd49afa3kagos9kb.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <span class="nav-item active">
           <p>Bienvenue <%= current_user.email %></p>
        </span>
      
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/dsmxleyf5/image/upload/v1606229210/qenaiz0yjkczpsl8fcvw.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <% if current_user.hauntedhouses %>
            <%= link_to "Afficher mes biens", hauntedlist_hauntedhouses_path, class: "dropdown-item" %>
            <%end %>
             <%= link_to "Louer votre Maison", new_hauntedhouse_path, class: "dropdown-item" %>
            <%= link_to "Mes réservations", journeys_path, class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

            
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div id="search" class="searchbar">
<%= form_tag hauntedhouses_path(anchor: "search"), method: :get, html: {id: "search"} do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Plutôt fantôme ou démon ? Maison ou château ?"
  %>
  <div class="search-btn">
  <%= submit_tag "Cherchez", class: "btn btn-dark" %>
<% end %>
</div>
</div>